// Generated by CoffeeScript 1.7.1
var CircularBuffer;

module.exports = CircularBuffer = (function() {
  function CircularBuffer(size) {
    this.size = size != null ? size : 65536;
    this.buffer = new Buffer(this.size);
    this.length = 0;
    this.start = 0;
    this.end = 0;
  }

  CircularBuffer.prototype.write = function(data) {
    var length, space;
    length = data.length;
    space = this.size - this.end;
    if (length > space) {
      data.copy(this.buffer, this.end, 0, space);
      data.copy(this.buffer, 0, space);
      this.end = length - space;
    } else {
      data.copy(this.buffer, this.end);
      this.end += length;
    }
    return this.length += length;
  };

  CircularBuffer.prototype.peek = function(amount) {
    var out, space;
    out = new Buffer(amount);
    space = this.size - this.start;
    if (amount < space) {
      this.buffer.copy(out, 0, this.start, this.start + amount);
    } else {
      this.buffer.copy(out, 0, this.start, this.size);
      this.buffer.copy(out, space, 0, amount - space);
    }
    return out;
  };

  CircularBuffer.prototype.read = function(amount) {
    var out, space;
    out = new Buffer(amount);
    space = this.size - this.start;
    if (amount < space) {
      this.buffer.copy(out, 0, this.start, this.start += amount);
    } else {
      this.buffer.copy(out, 0, this.start, this.size);
      this.buffer.copy(out, space, 0, this.start = amount - space);
    }
    this.length -= amount;
    return out;
  };

  return CircularBuffer;

})();
