// Generated by CoffeeScript 1.7.1
var a, b, time;

a = null;

b = null;

time = function(f, n) {
  var hrt, i, t, _i;
  if (n == null) {
    n = 1000000;
  }
  t = 0;
  for (i = _i = 0; _i < n; i = _i += 1) {
    hrt = process.hrtime();
    f();
    hrt = process.hrtime(hrt);
    t += hrt[1];
  }
  return t;
};

console.log(time(function() {
  var c;
  return c = [].concat(a, b);
}));

console.log(time(function() {
  var c;
  c = a;
  if (c != null) {
    if (b != null) {
      return c = c.concat(b);
    }
  } else {
    return c = b;
  }
}));
