// Generated by CoffeeScript 1.7.1
var Connection, Dispatch, net, proxyServer;

net = require('net');

Dispatch = require('./dispatch');

Connection = require('./connection');

module.exports = proxyServer = (function() {
  function proxyServer() {
    this.server = net.createServer(function(socket) {
      var dispatch, proxy;
      dispatch = new Dispatch;
      dispatch.load('core');
      // dispatch.load('responsive');
      // dispatch.load('tp');
      // dispatch.load('dmgspy');
      dispatch.load('outfitlogger');
      dispatch.load('arborean-apparel');
      dispatch.load('inventory');
      dispatch.load('logger');
      proxy = new Connection(socket, dispatch);
      proxy.connect({
        host: '208.67.49.68',
        port: 10001
      });
      return dispatch.connection = proxy;
    });
    this.server.on('listening', (function(_this) {
      return function() {
        var address;
        address = _this.server.address();
        return console.log("[server] listening on " + address.address + ":" + address.port);
      };
    })(this));
    this.server.listen(9247);
  }

  return proxyServer;

})();

new proxyServer;
